const ROLES = {
  FARMER: "FARMER",
  LEAD_FARMER: "LEAD_FARMER",
  SCOUT: "SCOUT",
  MANDAL_OFFICER: "MANDAL_OFFICER",
  DISTRICT_COORDINATOR: "DISTRICT_COORDINATOR",
  SCIENTIST: "SCIENTIST",
  WEATHER_SCIENTIST: "WEATHER_SCIENTIST",
  ADMIN: "ADMIN",
};

module.exports = { ROLES };